# Generated by Django 4.0 on 2022-11-23 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_schedule_oneday'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Schedule_oneday',
            new_name='Schedule',
        ),
    ]
