# Generated by Django 4.1 on 2022-10-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_doctor_delete_patient_remove_user_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_group',
            field=models.CharField(default='Patient', max_length=10),
        ),
    ]
