# Generated by Django 4.0 on 2022-11-24 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_schedule_oneday_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='day',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='hours',
        ),
        migrations.AddField(
            model_name='schedule',
            name='fri_hours',
            field=models.CharField(default='000000000', max_length=9),
        ),
        migrations.AddField(
            model_name='schedule',
            name='mon_hours',
            field=models.CharField(default='000000000', max_length=9),
        ),
        migrations.AddField(
            model_name='schedule',
            name='thu_hours',
            field=models.CharField(default='000000000', max_length=9),
        ),
        migrations.AddField(
            model_name='schedule',
            name='tue_hours',
            field=models.CharField(default='000000000', max_length=9),
        ),
        migrations.AddField(
            model_name='schedule',
            name='wed_hours',
            field=models.CharField(default='000000000', max_length=9),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.doctor', unique=True),
        ),
    ]
