# Generated by Django 4.0 on 2022-11-24 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_schedule_day_remove_schedule_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='week',
            field=models.DateField(default='2022-11-28'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
