# Generated by Django 4.0 on 2022-11-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_schedule_week_alter_appointment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='working_schedule',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
