# Generated by Django 4.0 on 2022-11-28 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='working_schedule',
        ),
    ]
