# Generated by Django 4.1 on 2022-10-21 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_doctor_name_doctor_phone_number_doctor_surname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='assigned_doctor',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_patients', to='users.doctor'),
        ),
    ]
