# Generated by Django 4.0 on 2022-11-29 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='email',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='IIN',
            field=models.IntegerField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='department_ID',
            field=models.IntegerField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='gov_id',
            field=models.IntegerField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='rating',
            field=models.IntegerField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='patient',
            name='IIN',
            field=models.IntegerField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=2),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gov_id',
            field=models.IntegerField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='patient',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('married', 'Married'), ('separeted', 'Separeted'), ('single', 'Single'), ('widowed', 'Widowed')], max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='registration_date',
            field=models.DateField(default=datetime.datetime(2022, 11, 29, 14, 5, 50, 62041)),
        ),
    ]
