# Generated by Django 4.0 on 2022-12-03 17:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_patient_email_alter_doctor_iin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='registration_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 3, 17, 1, 17, 940658)),
        ),
    ]
