# Generated by Django 4.0 on 2022-12-05 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_patient_registration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='department_ID',
        ),
        migrations.AlterField(
            model_name='patient',
            name='registration_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 5, 12, 37, 39, 964798)),
        ),
    ]
