# Generated by Django 4.1 on 2022-10-21 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_treatments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Treatments',
            new_name='Treatment',
        ),
    ]
