# Generated by Django 4.0 on 2022-12-07 10:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_doctor_department_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='medical_service',
            field=models.CharField(choices=[('consultation', 'Consultation'), ('examination', 'Examination'), ('treatment', 'Assign new treatment')], default='consultation', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='registration_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 7, 10, 14, 58, 931385)),
        ),
    ]
