# Generated by Django 4.0 on 2022-12-07 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_appointment_medical_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='registration_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 7, 10, 20, 4, 406646)),
        ),
    ]
