# Generated by Django 4.0 on 2022-12-07 14:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_patient_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='registration_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 7, 14, 24, 16, 830315)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='week',
            field=models.DateField(default='2022-12-05'),
        ),
    ]
