# Generated by Django 4.1 on 2022-11-03 05:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_patient_assigned_doctor_doctor_middle_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='IIN',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='doctor',
            name='address',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='doctor',
            name='appointment_price',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='doctor',
            name='category',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='doctor',
            name='date_of_birth',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='department_ID',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='doctor',
            name='education',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='doctor',
            name='experience',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='doctor',
            name='gov_id',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='doctor',
            name='homepage',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='rating',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='doctor',
            name='spec_ID',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
