# Generated by Django 4.1 on 2022-11-03 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_doctor_iin_doctor_address_doctor_appointment_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='assigned_doctor',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_patients', to='users.doctor'),
        ),
    ]
