# Generated by Django 4.1 on 2022-11-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_patient_assigned_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='assigned_doctor',
        ),
        migrations.AddField(
            model_name='doctor',
            name='working_schedule',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
