# Generated by Django 4.1 on 2022-11-04 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_patient_assigned_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='assigned_doctor',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='homepage',
            field=models.URLField(blank=True),
        ),
    ]
