# Generated by Django 4.1 on 2022-11-04 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_remove_patient_assigned_doctor_alter_doctor_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='assigned_doctor',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_patients', to='users.doctor'),
        ),
    ]
