# Generated by Django 4.1 on 2022-11-07 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_chats_alter_doctor_photo_messages_chats_doctor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatrooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatrooms', to='users.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatrooms', to='users.patient')),
            ],
        ),
        migrations.AlterField(
            model_name='messages',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='users.chatrooms'),
        ),
        migrations.DeleteModel(
            name='Chats',
        ),
    ]
