# Generated by Django 4.1 on 2022-11-07 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_chatrooms_alter_messages_chat_delete_chats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='chat',
            new_name='chatroom',
        ),
    ]
