# Generated by Django 4.1 on 2022-11-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_rename_chat_messages_chatroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='username',
            field=models.CharField(default='no_username', max_length=50),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='medicaments',
            field=models.CharField(default='Medicements empty', max_length=50),
        ),
    ]
